# KNN
* The k nearest neighbours algorithm can be used to solve both classification and regression problems
* K nearest works based on a similarity measures eg distance function
* There are Multiple distance functions like euclidean,Minkowski,Manhattan

# Problem statement
* we are given with a dataset which contains weather and temperature feature and Play target values.We have to predict weather it is possible to play on certain weather and temp conditions

In [3]:

#importing libraries 
#pandas for loading data and manipulation
#numpy for working with multidimensional arrays and matrices
#sklearn is machine learning library where all the methods related to ML algorithms can be imported

import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier 

#First Feature
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']
# Second Feature
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

# Label or target varible
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [4]:
#Preprocessing is package used to change raw feature vectors into a representation that is 
#more suitable for the downstream estimators.
from sklearn import preprocessing
le=preprocessing.LabelEncoder()#LabelEncoder is used to convert from string to int values(0,1,2..)
weather_feature=le.fit_transform(weather)#Converting weather features string into int[overcast=0,Rainy=1,sunny=2]
temp_feature=le.fit_transform(temp)#Converting temp features string into int[cool=0,Hot=1,Mild=2]
play_label=le.fit_transform(play)#Converting play label string into int[No=0,yes=1]



In [5]:
weather_feature

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1], dtype=int64)

In [6]:
temp_feature

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2], dtype=int64)

In [7]:
play_label

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [8]:
features=list(zip(weather_feature,temp_feature)) #Ziping the weather and temp features into list of tupples 

In [9]:
features

[(2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2)]

In [10]:
knn=KNeighborsClassifier(n_neighbors=3)#Calling KNeighborsClassifier with neighbours 3
knn.fit(features,play_label)#fitting the data

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [19]:
predicted=knn.predict([[2,2]]) #predicting the value [2,2] which is sunny and mild = yes(Play)

In [13]:
predicted

array([1], dtype=int64)

In [ ]:
#Hence the child can play when weather is sunny and mild